HobbyManager.WebMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HobbyManager.WebMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Mr. Cement S.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Instructions()
        {
            return View();
        }
    }
}

HobbyManager.WebMVC/Controllers/PaintController.cs
using HobbyManager.Models.Paint;
using HobbyManager.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HobbyManager.WebMVC.Controllers
{
    [Authorize]
    public class PaintController : Controller
    {
        // GET: Paint
        public ActionResult Index()
        {
            var service = CreatePaintService();
            var model = service.GetPaints();
            
            return View(model);
        }

        // GET: PaintCreate
        public ActionResult Create()
        {
            return View();
        }

        // POST: PaintCreate
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PaintCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreatePaintService();

            if (service.CreatePaint(model))
            {
                TempData["SaveResult"] = "Your paint was successfully created.";
                return RedirectToAction("Index");
            };

            ModelState.AddModelError("", "Paint could not be created.");

            return View(model);
        }

        // GET: Details
        public ActionResult Details(int id)
        {
            var svc = CreatePaintService();
            var model = svc.GetPaintById(id);

            return View(model);
        }

        //GET: PaintEdit
        public ActionResult Edit(int id)
        {
            var service = CreatePaintService();
            var detail = service.GetPaintById(id);
            var model =
                new PaintEdit
                {
                    PaintId = detail.PaintId,
                    Brand = detail.Brand,
                    Name = detail.Name,
                    Color = detail.Color,
                    SKU = detail.SKU
                };
            return View(model);
        }

        //POST: PaintEdit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, PaintEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if(model.PaintId != id)
            {
                ModelState.AddModelError("", "Id did not match.");
                return View(model);
            }

            var service = CreatePaintService();

            if (service.UpdatePaint(model))
            {
                TempData["SaveResult"] = "Your paint was successfully updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your paint could not be updated.");
            return View(model);
        }

        //GET: PaintDelete
        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreatePaintService();
            var model = svc.GetPaintById(id);

            return View(model);
        }

        //POST: PaintDelete
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePaint(int id)
        {
            var service = CreatePaintService();

            service.DeletePaint(id);

            TempData["SaveResult"] = "Your note was successfully deleted.";

            return RedirectToAction("Index");
        }

        private PaintService CreatePaintService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new PaintService(userId);
            return service;
        }
    }
}

HobbyManager.WebMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<div class="text-wrapper">
    <h2>@ViewBag.Title.</h2>
    <h3>About Hobby Manager</h3>

    <p>Hobby Manager allows scale modelers or miniature wargame players to track their projects, and go-to paint recipes. Users can input their paint collection, assign paints to Workflows, and add these workflows to their projects. Users can save their paints used to paint specific objects in the order in which they are applied to the subject. For example, if you are painting a uniform, you can input the primer you used for the model, your base paint, the shade or wash you used, your first highlight color, and your second highlight color. This allows you to come back to your project later and have a record of which paints you used and the order you applied them.</p>

</div>

HobbyManager.WebMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<div class="text-wrapper">
    <h2>@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        <strong>Support:</strong>   <a href="mailto:snake1998@foxhound.com">snake1998@foxhound.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:snake1998@foxhound.com">snake1998@foxhound.com</a>
    </address>
</div>

HobbyManager.WebMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>@ViewBag.Title</h1>
    <p class="lead">Hobby Manager is a free web MVC app that allows users to track their hobby projects with a focus on the paints and processes used.</p>
    @Html.ActionLink("Learn More", "About")
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Instructions</h2>
        <p>Please take a moment to read through the instructions before you begin.</p>
        <p>@Html.ActionLink("Instructions", "Instructions", null, new { @class = "btn btn-primary btn-large" })</p>
    </div>
    <div class="col-md-4">
        <h2>Start here!</h2>
        <p>
            Not sure where to start? Begin by adding some of your paint collection to the database!
        </p>
        <p>@Html.ActionLink("Add Paints", "Index", "Paint", null, new { @class = "btn btn-primary btn-large" })</p>
    </div>
    <div class="col-md-4">
        <h2>Need Inspiration?</h2>
        <p>Check out some of my personal projects on my Instagram!</p>
        <p><a class="btn btn-default" href="https://www.instagram.com/rc1107delta/">Get Inspired! &raquo;</a></p>
    </div>
</div>

HobbyManager.WebMVC/Views/Home/Instructions.cshtml
@{
    ViewBag.Title = "Instructions";
}
<div class="text-wrapper">
    <h2>@ViewBag.Title.</h2>
    <h3>Instructions</h3>

    <p>To succesfully use Hobby Manager, you will need to do things in a certain order to avoid errors. But first, let's define our terms:</p>
    <ul>
        <li>Paint: As you may have guessed, this is a single paint. You'll add paints to Workflows to save your "recipes" for colors.</li>
        <li>Model: This is the object you are currently working on, be it armor, an aircraft, a squad of infantrymen, etc.</li>
        <li>Project: This represents your overall project. Are you working on a diorama? An army for a miniatures wargame?</li>
        <li>Workflow: These are your paint recipes. For example, if you paint a leather pouch on an orc, and you really like the way it turned out, you can record the paints you used, in the order that you used them, to refer back to in the future.</li>
        <li>ProjectModel: This is simply a place to link a project with the models you are using for that project.</li>
        <li>ProjectWorkflow: This is a place to link the Workflows you used for a specific project.</li>
    </ul>
    <p>To start, you should begin by adding your paint collection to the database. This allows us to create workflows later! Once you've got some of your paints entered, you can create workflows using those paints. <br /> <br /> After you've added your paints, try adding a Model that you're working on, and create a Project. <br /> <br /> Once you've created a Model and a Project, start creating Workflows. Once you've created at least one Workflow, try linking a Model to a Project using the ProjectModel tab, or link a Workflow to a Project using the ProjectWorkflow tab.</p>

</div>